# Generated by Django 6.0.1 on 2026-01-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0002_alter_menu_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
