# Generated by Django 6.0.1 on 2026-01-29 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0003_menu_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="category",
            field=models.CharField(
                choices=[
                    ("Appetizer", "Appetizer"),
                    ("Main Course", "Main Course"),
                    ("Dessert", "Dessert"),
                    ("Beverage", "Beverage"),
                ],
                default="Main Course",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="Description",
            field=models.TextField(help_text="Enter product description here"),
        ),
        migrations.AlterField(
            model_name="menu",
            name="Name",
            field=models.CharField(
                help_text="Enter the product name here.", max_length=200
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["category"], name="rest_app_me_categor_5b7a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(
                fields=["is_available"], name="rest_app_me_is_avai_530975_idx"
            ),
        ),
    ]
