# Generated by Django 6.0.1 on 2026-01-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0004_alter_menu_options_menu_category_menu_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="Image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="Price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="Name",
        ),
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.TextField(
                blank=True, help_text="Enter the Descrption if the menu item", null=True
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(
                default="menu item",
                help_text="Enter the name of the menu item",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
